--- rust/bridge/shared/Cargo.toml.orig	2023-08-15 15:46:43.150761000 +0200
+++ rust/bridge/shared/Cargo.toml	2023-08-15 15:46:54.578123000 +0200
@@ -40,7 +40,7 @@ neon = { version = "0.10.0", optional = true, default-
 libc = { version = "0.2", optional = true }
 jni_crate = { version = "0.19", package = "jni", optional = true }
 neon = { version = "0.10.0", optional = true, default-features = false, features = ["napi-6", "promise-api"] }
-linkme = { version = "0.3.9", optional = true }
+linkme = { version = "0.3.0", optional = true }
 signal-neon-futures = { path = "../node/futures", optional = true }
 
 [features]
